version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  flask:
    depends_on:
      - redis
    deploy:
      replicas: 3 # scale the flask service to multiple instances
    build:
      context: .
    ports:
      - "5000" # expose container port 5000 only
    environment:
      - REDIS_HOST=redis

  nginx: # load balancer for the Flask instances
    depends_on:
      - flask
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  redis-data:
