version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  flask:
    depends_on:
      - redis
    build:
      context: .
    ports:
      - "5002:5000" # Map host port 5002 to container port 5000
    environment:
      - REDIS_HOST=redis

volumes:
  redis-data:
